#!/usr/bin/env node

const commander = require('commander');

const program = new commander.Command();
program.version("0.0.1");
program
    .command("db <cmd>", "Database functions")
    .command("conversations <cmd>", "Conversations functions")
    .command("messages <cmd>", "Messages functions")
    .parse(process.argv);

