#!/usr/bin/env node

const program = require("commander")

program
    .version("0.0.1")
    .command("tables", "List tables")
    .command("schemas", "Dump complete schema")
    .command("schema <schema>", "Show a single schema")
    .parse(process.argv);
