#!/usr/bin/env node

const program = require("commander")

program
    .version("0.0.1")
    .command("list <conversationId>", "List conversations")
    .command("cp <args>", "Show a conversation")
    .parse(process.argv);
